#!/usr/bin/env tsx

/**
 * Auto-Generate Blog Post with OpenAI (text) + Leonardo (image)
 * Generates complete articles with text and images for Pisicopedia.ro
 */

import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';
import { getOpenAIClient, ARTICLE_PROMPTS, validateAutoGeneratedContent, extractSlugFromContent, extractFrontmatter } from '../lib/ai-config';
import { generateArticleImage } from '../lib/leonardo-images';
import { getNextTopicForGeneration, AutoTopic } from '../lib/auto-topics';

// Load environment variables
dotenv.config({ path: '.env.local' });

// Colors for console output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
  magenta: '\x1b[35m',
};

// Get existing article slugs
function getExistingArticleSlugs(): string[] {
  const articlesDir = path.join(process.cwd(), 'content', 'articles');

  if (!fs.existsSync(articlesDir)) {
    return [];
  }

  const files = fs.readdirSync(articlesDir);
  return files
    .filter(file => file.endsWith('.mdx'))
    .map(file => file.replace('.mdx', ''));
}

// Generate article with OpenAI
async function generateArticleText(topic: AutoTopic): Promise<string> {
  console.log(`\n${colors.cyan}📝 Generating article text with OpenAI...${colors.reset}`);

  const client = getOpenAIClient();

  try {
    const response = await client.chat.completions.create({
      model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
      temperature: 0.7,
      max_tokens: 4000,
      messages: [
        {
          role: 'system',
          content: ARTICLE_PROMPTS.system
        },
        {
          role: 'user',
          content: ARTICLE_PROMPTS.generateArticle(topic)
        }
      ]
    });

    const content = response.choices[0]?.message?.content;

    if (!content) {
      throw new Error('No content generated from OpenAI');
    }

    console.log(`${colors.green}✅ Article text generated successfully${colors.reset}`);
    return content;

  } catch (error: any) {
    console.error(`${colors.red}❌ Failed to generate article text:${colors.reset}`, error.message);
    throw error;
  }
}

// Update frontmatter with image path
function updateFrontmatterWithImage(content: string, imagePath: string): string {
  return content.replace(/^(---[\s\S]*?)image:\s*""([\s\S]*?---)/m, `$1image: "${imagePath}"$2`);
}

// Save article to file
function saveArticle(slug: string, content: string): string {
  const articlesDir = path.join(process.cwd(), 'content', 'articles');

  // Ensure directory exists
  if (!fs.existsSync(articlesDir)) {
    fs.mkdirSync(articlesDir, { recursive: true });
  }

  const filePath = path.join(articlesDir, `${slug}.mdx`);
  fs.writeFileSync(filePath, content, 'utf-8');

  return filePath;
}

// Main auto-generation function
async function autoGeneratePost() {
  console.log(`\n${colors.bright}${colors.magenta}🤖 AUTO-BLOG GENERATOR FOR PISICOPEDIA.RO${colors.reset}`);
  console.log('='.repeat(60));

  // Check required API keys
  if (!process.env.OPENAI_API_KEY) {
    console.error(`${colors.red}❌ Error: OPENAI_API_KEY is not set in .env.local${colors.reset}`);
    process.exit(1);
  }

  if (!process.env.LEONARDO_API_KEY) {
    console.error(`${colors.red}❌ Error: LEONARDO_API_KEY is not set in .env.local${colors.reset}`);
    process.exit(1);
  }

  // Step 1: Get next topic
  console.log(`\n${colors.cyan}1️⃣ Selecting topic...${colors.reset}`);
  const existingSlugs = getExistingArticleSlugs();
  console.log(`   Found ${existingSlugs.length} existing articles`);

  const topic = getNextTopicForGeneration(existingSlugs);

  if (!topic) {
    console.log(`${colors.yellow}⚠️  No new topics available for generation${colors.reset}`);
    console.log('   All topics have been generated or no topics defined');
    process.exit(0);
  }

  console.log(`${colors.green}✅ Selected topic:${colors.reset} ${topic.title}`);
  console.log(`   Category: ${topic.category}`);
  console.log(`   Priority: ${topic.priority}`);
  console.log(`   Slug: ${topic.slug}`);

  try {
    // Step 2: Generate article text with OpenAI
    console.log(`\n${colors.cyan}2️⃣ Generating article text...${colors.reset}`);
    const articleContent = await generateArticleText(topic);

    // Validate generated content
    console.log(`\n${colors.cyan}3️⃣ Validating generated content...${colors.reset}`);
    const validation = validateAutoGeneratedContent(articleContent);

    if (!validation.valid) {
      console.error(`${colors.red}❌ Content validation failed:${colors.reset}`);
      validation.errors.forEach(error => console.error(`   - ${error}`));
      throw new Error('Invalid generated content');
    }

    if (validation.warnings.length > 0) {
      console.log(`${colors.yellow}⚠️  Validation warnings:${colors.reset}`);
      validation.warnings.forEach(warning => console.log(`   - ${warning}`));
    } else {
      console.log(`${colors.green}✅ Content validation passed${colors.reset}`);
    }

    // Extract slug and metadata
    const slug = extractSlugFromContent(articleContent) || topic.slug;
    const frontmatter = extractFrontmatter(articleContent);

    // Step 3: Generate image with Leonardo
    console.log(`\n${colors.cyan}4️⃣ Generating article image with Leonardo...${colors.reset}`);
    const imagePath = await generateArticleImage(
      slug,
      topic.title,
      topic.category,
      topic.subcategory
    );

    // Step 4: Update content with image path
    console.log(`\n${colors.cyan}5️⃣ Updating content with image path...${colors.reset}`);
    const finalImagePath = imagePath || `/images/articles/${slug}.jpg`;
    const finalContent = updateFrontmatterWithImage(articleContent, finalImagePath);

    // Step 5: Save article
    console.log(`\n${colors.cyan}6️⃣ Saving article...${colors.reset}`);
    const filePath = saveArticle(slug, finalContent);
    console.log(`${colors.green}✅ Article saved:${colors.reset} ${filePath}`);

    // Success summary
    console.log('\n' + '='.repeat(60));
    console.log(`${colors.bright}${colors.green}🎉 AUTO-GENERATION COMPLETE!${colors.reset}`);
    console.log('='.repeat(60));
    console.log(`📝 Article: ${topic.title}`);
    console.log(`📁 File: content/articles/${slug}.mdx`);
    console.log(`🖼️  Image: ${imagePath}`);
    console.log(`📊 Stats:`);

    if (frontmatter) {
      console.log(`   - Reading time: ${frontmatter.readingTime || 'N/A'}`);
      console.log(`   - Category: ${frontmatter.category}`);
      console.log(`   - Status: ${frontmatter.status}`);
    }

    console.log(`\n${colors.cyan}💡 Next steps:${colors.reset}`);
    console.log('   1. Run: npm run validate:content (to verify)');
    console.log('   2. Run: npm run build (to check build)');
    console.log('   3. Review the generated article');
    console.log('   4. Deploy when ready');

  } catch (error: any) {
    console.error(`\n${colors.red}❌ Auto-generation failed:${colors.reset}`, error.message);
    console.error('\nDebug info:', error);
    process.exit(1);
  }
}

// Run the auto-generation
autoGeneratePost().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});